[build]
  command = "pnpm build || ( npm install pnpm && pnpm build )"
  publish = "dist"
  #  environment = { NODE_VERSION = "16" }

[build.environment]
  # bypass npm auto install
  NPM_FLAGS = "--version"
  NODE_VERSION = "16"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Opting your Website out of Google's FLoC Network
[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[[redirects]]
  from = '/api/*'
  to = 'https://api.tangueros.net/:splat'
  status = 200
  force = true
  headers = {X-From = "Netlify"}
  signed = "API_SIGNATURE_TOKEN"

[[redirects]]
  from = '/blog/*'
  to = 'https://mindfultango.wordpress.com/:splat'
  status = 200
  force = true
  headers = {X-From = "Netlify"}
  signed = "API_SIGNATURE_TOKEN"
